default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_bdd_demo_development

test: &test
  <<: *default
  database: rails_bdd_demo_test

production:
  <<: *default
  database: rails_bdd_demo_production
  username: rails_bdd_demo
  password: <%= ENV['RAILS_BDD_DEMO_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
